version: 2
updates:
  # cdktf
  - package-ecosystem: "terraform"
    directory: "/cdktf"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/cdktf"
    schedule:
      interval: "daily"
  # terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
